### ISSUE TITLE
Block not working

### ISSUE THREAD

**Issue by abdullah1908** [pantheon-systems/github-gist-gutenberg-block#2]
Hi,

I am facing the issue while I drop the **Github Gist** block in the editor. It shows the following message. Please see the attached screenshot.
![block not working](https://user-images.githubusercontent.com/14175927/37729856-f6337d46-2d5f-11e8-9c5f-897e756e16a4.png)

WordPress: _4.9.4_
Gutenberg _2.4.0_
Thanks & Regards,
Abdullah
WP Engineer

**Comment by danielbachhuber** [comment]
Hi @abdullah1908,

Thanks for the report. Can you share any JavaScript errors you see in the console?

**Comment by abdullah1908** [comment]
Hello @danielbachhuber ,

Thanks for your response. I have attached the screenshot that is displaying console errors. Please have a look.
![console errors for github-gist-gutenberg-block](https://user-images.githubusercontent.com/14175927/37764241-02de9f16-2de3-11e8-834b-ac711df3088e.png)

Best Regards,
Abdullah

**Comment by danielbachhuber** [comment]
Thanks for the additional detail, @abdullah1908.

I've been able to reproduce and fix this error with #3. You'll see it in the just tagged v0.1.1 release.

**Comment by abdullah1908** [comment]
Thank you so much @danielbachhuber for your instant response and fix.
