### ISSUE TITLE
Lacking admin styling

### ISSUE THREAD

**Issue by GaryJones** [pantheon-systems/github-gist-gutenberg-block#5]
The plugin works with Gutenberg 3.9.0, though it doesn't have any styling in the editor like it does on the front end. This makes code harder to follow. For instance, there's no PHP syntax highlighting or indentation:

![screenshot 2018-10-12 09 31 50](https://user-images.githubusercontent.com/88371/46857813-b7476a00-ce01-11e8-8911-dcab1a42d05a.png)

Yet there is on the [front end](https://garyjones.io/move-floating-social-bar-genesis).

**Comment by danielbachhuber** [comment]
@GaryJones Thanks for the report! And sorry for my late reply; I'd meant to comment but lost track.

Want to submit a pull request for this?

**Comment by GaryJones** [comment]
> Want to submit a pull request for this?

My list of items is getting longer by the day, so I'm not likely to circle back to this any time soon I'm afraid.

**Comment by danielbachhuber** [comment]
As it turns out, we're going to archive this repository. The plugin was originally written for a blog post and not something we're planning to maintain long term.

**Comment by GaryJones** [comment]
No problems - any suggestions for similar plugins that are going to be maintained?

cc @bradyvercher - maybe we could fork this into GistPress?
